name: Sync with Upstream

on:
  schedule:
    # Run weekly on Sunday at midnight UTC
    - cron: "0 0 * * 0"

  workflow_dispatch: # Allows manual trigger of the workflow
    inputs:
      reason:
        description: "Reason for manual sync"
        required: false

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your fork repository
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for tags and branches

      # Step 2: Add upstream remote
      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/ocornut/imgui.git

      # Step 3: Fetch tags and branches from upstream
      - name: Fetch Upstream Tags and Branches
        run: git fetch upstream --tags

      # Step 4: Merge upstream/master into fork's master branch
      - name: Merge Upstream into Fork
        run: |
          git checkout master
          git merge upstream/master || echo "No new changes to merge."

      # Step 5: Push changes to your fork
      - name: Push Changes to Fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin master
          git push origin --tags

